#!/usr/bin/env bash
# This script is used to install nginx

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemct1 status nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
