#!/usr/bin/env bash
# This script is used to install nginx

sudo apt insttall -y nginx
echo <<EOL | root hello.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

EOL

server {
    listen 80;
    location / {
        root hello.html;
    }
}
