#!/usr/bin/env bash
# script to install and setup nginx
CONFIG_FILE="/etc/nginx/sites-available/default"

# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Hello World!' > /usr/share/nginx/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://example.com/new_page; # Update to the correct URL
    }
}" > $CONFIG_FILE

# Reload Nginx to apply the new configuration
nginx -s reload

