#!/usr/bin/env bash
#configures a new Ubuntu machine nginx

sudo apt update
sudo apt install haproxy -y

echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 342949-web-01 54.196.35.48:80 check
        server 342949-web-02 34.229.66.60:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
