#!/usr/bin/env bash
#This file answers the questions, the type of network in a local computer
#type of network to connect an office in one building to one far away
#what network is used to browse

3
2
1
