#!/usr/bin/env bash
#This file works with the start, stopand restart process

cmd="$1"

if [ -r "$cmd" ];
then
    echo "Usage: manage_my_process {start|stop|restart}"
fi

if [ "$cmd" == "start" ];
then
    bash ./manage_my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "$cmd" == "stop" ];
then
    [ -e "/var/run/my_process.pid" ] && pkill -f /
    './manage_my_process' && rm /var/run/my_process.pid
    echo "manage_my_process stopped"

elif [ "$cmd" == "restart" ];
then
    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
