#!/usr/bin/env bash
#This file works with the start, stopand restart process

command="$1"
pid_file="/var/run/my_process.pid"

case "$command" in
  start)
    bash ./manage_my_process &
    echo "$!" > "$pid_file"
    echo "manage_my_process started"
    ;;
  stop)
    if [ -e "$pid_file" ]; then
      pkill -f './manage_my_process' && rm "$pid_file"
      echo "manage_my_process stopped"
    else
      echo "manage_my_process is not running"
    fi
    ;;
  restart)
    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
