#!/usr/bin/env bash
#This file runs an infinite loop that sleeps after every
#iteration

i=1

trap 'echo "I am invincible!!!"' SIGTERM
while [ $i -gt 0 ];
do
    echo "To infinity and beyond"

    sleep 2
done
