#!/usr/bin/env bash
# This script displays messages and to infinty

function trap_handler {
  echo "I am invincible!!!"
}

trap trap_handler SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
