#!/usr/bin/env bash
# This script displays the content of /etc/passwd with specific information.

gid="_"
gecos="gecos"
shell="shell"
while IFS=':' read -r username _ uid 100-read_and_cut100-read_and_cutgid gecos home shell
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
