#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# where only the part of the name after the first dash is displayed.

for item in *
do
    if [[ -f $item && $item != .* && $item == *-* ]]; then
        echo "${item#*-}"
    fi
done

