#!/usr/bin/env bash
# This file gives information about the school file

a_file="school"

if [ -e "$a_file" ]; then
    echo "school file exists"

    if [ -s "$a_file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$a_file" ]; then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi
